varnombre = input ("Escriba su nombre completo")
dividirnombre= varnombre.split()
primerletra = dividirnombre[0][0].upper()
segundapalabra = dividirnombre[1].upper()
print (f"{varnombre.lower()}\n {varnombre.upper()}\n {primerletra} {segundapalabra}")